services:
  mysql:
    image: mysql:9
    environment:
      MYSQL_DATABASE: user_logs
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - ${DATABASE_PORT}
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db_data:
